[build]
  publish   = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options            = "SAMEORIGIN"
    X-XSS-Protection           = "1; mode=block"
    X-Content-Type-Options     = "nosniff"
    Referrer-Policy            = "strict-origin-when-cross-origin"
    Permissions-Policy         = "autoplay=(*), fullscreen=(*), microphone=()"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
